apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-listener-svc-config
data:
  source_topic: bobbycar-gps
  client_id: kafka-listener-svc
  group_id: kafka-listener-svc
  kafka_service: 'bobbycar-cluster-kafka-bootstrap.bobbycar.svc.cluster.local'
  kafka_service_port: '9092'
